### PR TITLE
Introduce tests of emitted events and fix a few bugs found along the way

### LINKED ISSUE #13: Add basic tests
There are currently zero tests for the code. That's not a huge problem in itself since there's not that much code and not too many conditionals that make exhaustive manual testing prohibitive, but we have lots of features lined up and we'll want to be able to make those changes with confidence.

### PR DESCRIPTION
**Pull request by magnusbaeck**
This PR adds tests to check the contents of the emitted events for a couple of common job types (freestyle, matrix, pipeline). To make writing the tests less painful the event classes are refactored to actually model the Eiffel events instead of storing the event data in hashmaps. This should also simplify future expansions of the event contents (causes etc) and make it less error-prone. Fixes #13.

I'm sorry for this huge PR, but I've at least tried to split all logical changes into different commits. I recommend that you look at the individual commits rather than the diff of the whole PR.

### CODE REVIEW

**Review by Isacholm — APPROVED** [review]

File: src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Mocks.java [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+
+/**
+ * Test mocks.
+ *
+ * @author Örjan Percy &lt;orjan.percy@sonymobile.com&gt;
+ * @author Magnus Bäck &lt;magnus.back@axis.com&gt;
+ */
+final class Mocks {
+    /** Stores received messages. */
+    public static final List<String> MESSAGES = new CopyOnWriteArrayList<>();
```
Comment (GLundh) [inline src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Mocks.java:42]: No big deal, but only immutables should be uppercase, even if `final const`. If I had not already read this code in mq-notifier, I would have been surprised to see it changed in `EmittedEventsTest.` For similar reasons `final static Logger logger` is preferred over `final const Logger LOGGER`.

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java [hunk 2]
```diff
@@ -45,11 +44,23 @@ of this software and associated documentation files (the "Software"), to deal
  */
 @Extension
 public class QueueListenerImpl extends QueueListener {
+    private static final Logger LOGGER = LoggerFactory.getLogger(QueueListenerImpl.class);
```
Comment (GLundh) [inline src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java:44]: It's no big deal, but a pet peeve of mine: https://stackoverflow.com/questions/1417190/should-a-static-final-logger-be-declared-in-upper-case

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java [hunk 3]
```diff
@@ -73,23 +74,23 @@ public static String getFullName(Queue.Task t) {
...
-     * @return Epoch time in milliseconds
-     */
-    public static long getTime() {
-        return Instant.now().toEpochMilli();
+    public static void publishEvent(EiffelEvent event) {
+        EiffelBroadcasterConfig config = EiffelBroadcasterConfig.getInstance();
+        if (config != null && config.isBroadcasterEnabled()) {
+            AMQP.BasicProperties props = new AMQP.BasicProperties.Builder()
+                    .appId(config.getAppId())
+                    .deliveryMode(config.getPersistentDelivery() ? 2 : 1)
```
Comment (GLundh) [inline src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java:83]: Can we get rid of the magic numbers?

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java [hunk 4]
```diff
@@ -24,65 +24,90 @@ of this software and associated documentation files (the "Software"), to deal
...
-    * Constructor of EiffelActivityCanceledEvent.
-    * @param activityExecutionId
-    * event id of the EiffelActivityStartedEvent that was canceled.
-    */
-    public EiffelActivityCanceledEvent(String activityExecutionId) {
-        super();
-        super.setEventData(initEventData());
-        super.setEventLinks(initEventLinks(activityExecutionId));
+    @JsonInclude(JsonInclude.Include.ALWAYS)
+    private Data data;
```
Comment (GLundh) [inline src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java:42]: final?

Comment (GLundh) [reply src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java:42]: Probably goes for the rest of the POJOs

File: src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EventSet.java [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+     * Finds the first event of a particular class that matches a condition, pops it from
+     * the event set, and returns it.
+     *
+     * @param clazz the class to look for
+     * @param matcher a {@link Matcher} that will be evaluated against the list of
+     * @return the first matching event
+     * @throws java.util.NoSuchElementException if no event matching the condition could be found
+     */
+    public <T> T findNext(Class<T> clazz, Matcher<EiffelEvent> matcher) {
+        T event = events.stream()
```
Comment (GLundh) [inline src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EventSet.java:85]: .filter(clazz::isInstance)
                .filter(matcher::matches)
                .map(clazz::cast)
                .findFirst()
                .get();

**Review by GLundh — APPROVED** [review]
Optional nits. 

Q: Why are there not versioned and (de)serializable eiffel event POJOs already available as maven deps? It seems stupid that every plugin needs to build their own...?

Great changes though.

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java (hunk 4 above)
Comment (magnusbaeck) [reply src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/eiffel/EiffelActivityCanceledEvent.java]: Yes, good call. Done.

File: src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EventSet.java (hunk 5 above)
Comment (magnusbaeck) [reply src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EventSet.java:85]: Done.

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java (hunk 3 above)
Comment (magnusbaeck) [reply src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java]: Done.

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java (hunk 2 above)
Comment (magnusbaeck) [reply src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/QueueListenerImpl.java]: Fixed in a new prequel commit.

File: src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Mocks.java (hunk 1 above)
Comment (magnusbaeck) [reply src/test/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Mocks.java]: Done.

**Comment by GLundh** [comment]
I hate that I cannot diff between forcepushes in a PR in an easy way :/

**Comment by GLundh** [comment]
Anyways. LGTM.

**Comment by magnusbaeck** [comment]
> I hate that I cannot diff between forcepushes in a PR in an easy way :/

Yeah, sorry about that. I'm still amazed that Github doesn't allow series of commits to be reviewed in a reasonable way.

> Q: Why are there not versioned and (de)serializable eiffel event POJOs already available as maven deps? It seems stupid that every plugin needs to build their own...?

Yeah. There's [eiffel-remrem-semantics](https://github.com/eiffel-community/eiffel-remrem-semantics) but it drags in quite a few dependencies (JGit, the Logback backend (!)) and I figured it'd be easy enough to define the classes here. In the end they grew a bit larger than anticipated so it was perhaps misguided.
