### PR TITLE
Fix startup race condition that put the outbound message queue in a bad state

### LINKED ISSUE #81: MQConnection can get into an unrecoverable state during startup
### Jenkins and plugins versions report

Custom Docker image based on Jenkins 2.346.3<br>
eiffel-broadcaster 2.4.0

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 18.04.6

### Reproduction steps

1. Install and configure the plugin on a Jenkins controller.
2. Restart the controller.

### Expected Results

Plugin fires up nicely and starts publishing events.

### Actual Results

The plugin attempts to send an event before [EiffelBroadcasterConfig](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/eiffel-broadcaster-2.4.0/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java), a GlobalConfiguration subclass, has been configured. At that time the AMQP URL is still null and we get an NPE in the MQConnection#messageQueueThread thread.

```
2022-12-01 08:26:29.292+0000 [id=104]   SEVERE  h.i.i.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler#uncaughtException: A thread (Thread-17/104) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
        at java.base/java.net.URI$Parser.parse(URI.java:3104)
        at java.base/java.net.URI.<init>(URI.java:600)
        at com.rabbitmq.client.ConnectionFactory.setUri(ConnectionFactory.java:379)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.getConnectionFactory(MQConnection.java:349)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.getConnection(MQConnection.java:378)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.createChannel(MQConnection.java:301)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.sendMessages(MQConnection.java:252)
        at com.sonymobile.jenkins.plugins.mq.mqnotifier.MQConnection.lambda$addMessageToQueue$0(MQConnection.java:209)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Within a few seconds the configuration is in place, but because of another bug in [MQConnection#addMessageToQueue](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/eiffel-broadcaster-2.4.0/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java#L163) it attempts to restart the old dead thread instead of recreating it, resulting in another exception:

```
2022-12-01 08:26:35.250+0000 [id=53]    WARNING jenkins.util.Listeners#lambda$notify$0
java.lang.IllegalThreadStateException
        at java.base/java.lang.Thread.start(Thread.java:789)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.MQConnection.addMessageToQueue(MQConnection.java:180)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.Util.mustPublishEvent(Util.java:138)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.Util.mustPublishEvent(Util.java:159)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.Util.publishEvent(Util.java:171)
        at com.axis.jenkins.plugins.eiffel.eiffelbroadcaster.RunListenerImpl.onCompleted(RunListenerImpl.java:131)
        at hudson.model.listeners.RunListener.lambda$fireCompleted$0(RunListener.java:207)
        at jenkins.util.Listeners.lambda$notify$0(Listeners.java:59)
        at jenkins.util.Listeners.notify(Listeners.java:67)
        at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:205)
        at hudson.model.Run.execute(Run.java:1933)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
        at hudson.model.ResourceController.execute(ResourceController.java:101)
        at hudson.model.Executor.run(Executor.java:442)
```

### Anything else?

The NPE as well as the thread restart problem should be easy enough to fix, but the MQ Notifier plugin received a significant revamp of its AMQP sending code in https://github.com/jenkinsci/mq-notifier-plugin/pull/30 so we should port those changes here instead. This plugin basically started out as a fork of MQ Notifier so the patches should apply without too much trouble. That'll also bring a number of other improvements. We run MQ Notifier on the same host where we had issues with this plugin and MQ Notifier wasn't affected. It's of course possible that we only were lucky with MQ Notifier (such is the nature of race conditions) but I suspect the reason actually is more robustness in that plugin.

cc: @hampusjohansson1

### PR DESCRIPTION
**Pull request by magnusbaeck**
For some time there's been a race condition during Jenkins startup between the sending of the first event and the initialization of the message queue thread.

The AMQP configuration is passed to MQConnection via initialized(), called from EiffelBroadcasterConfig#configure(). Until this has happened, the MQConnection's AMQP URL will be null and any attempt to send an event will trigger an NPE. To make matters worse, the message queue thread startup code in MQConnection#addMessageToQueue() had a bug it would attempt to restart a crashed thread rather than create a new one, resulting in an IllegalStateException.

We solve this by introducing an MQConnection#initialized attribute that's set to true only after we've received the configuration, and until then the message queue thread won't be started. We still post messages to the queue, though, so any early messages will still be sent.

While we're at it we solve the bug that resulted in the IllegalStateException, allowing a crashed message queue thread to be recoverable.

I couldn't find a good way of testing this bugfix. Verifying a startup race condition with a JenkinsRule-based instance isn't obvious and while it'd be easy to add a unit test for the MQConnection class, it's a singleton class so we only get one shot per test session.

Fixes #81

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by magnusbaeck** [comment]
Gah, forgot to run SpotBugs locally. Current commit will be amended.

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java [hunk 1]
```diff
@@ -205,6 +190,29 @@ private void sendMessages() {
...
 
+    /**
+     * Start or restart the message queue thread as necessary. Requires that
+     * the MQConnection has been initialized with the needed configuration.
+     *
+     * @return true if the message queue thread was started, otherwise false
+     */
+    private boolean startMessageQueueThread() {
+        synchronized (lock) {
+            if (!initialized || (messageQueueThread != null && messageQueueThread.isAlive())) {
```
Comment (GLundh) [inline src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java:201]: Hmm.. I wonder if the `initialized` variable can see an old thread cached value since `public void initialize()`is set from a non synchronized block. Making the var volatile should solve that issue. Not sure if it is necessary though.

**Review by GLundh — APPROVED** [review]
Nice work. The solution seems straight forward enough to me. I approve since I'm not 100% sure about my comment. Do what you want with it.

File: src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java (hunk 1 above)
Comment (magnusbaeck) [reply src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/MQConnection.java:201]: Ah, excellent point! I totally forgot about synchronization of `initialized`. I think you're right that we need volatile, although the consequences of caching would only be that the thread gets to start slightly later, which in most cases won't be a problem. But let's fix it anyway. I've pushed an extra commit. Will squash the branch into a single commit when merging.

**Review by GLundh — APPROVED** [review]
